{
 "title": "Envoy Ingress Connections",
 "description": "Envoy Ingress Connections",
 "tags": [
  "envoy",
  "ingress"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_time_sum[1m]))",
     "legendFormat": "request sum"
    },
    {
     "expr": "sum(rate(envoy_http_downstream_rq_time[1m]))",
     "legendFormat": "request"
    },
    {
     "expr": "sum(rate(envoy_http_downstream_rq_time_bucket[1m]))",
     "legendFormat": "request bucket"
    },
    {
     "expr": "sum(rate(envoy_http_downstream_rq_time_count[1m]))",
     "legendFormat": "request count"
    }
   ]
  },
  {
   "title": "Packetsize",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_cx_rx_bytes_total[1m]))",
     "legendFormat": "received"
    },
    {
     "expr": "sum(rate(envoy_http_downstream_cx_tx_bytes_total[1m]))",
     "legendFormat": "transmitted"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_cx_active[1m]))",
     "legendFormat": "active"
    },
    {
     "expr": "sum(rate(envoy_http_downstream_cx_total[1m]))",
     "legendFormat": "total"
    }
   ]
  }
 ]
}