{
 "title": "Envoy Service",
 "description": "Envoy Service Dashboard",
 "tags": [
  "envoy",
  "test"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "originating_service",
    "label": "Originating Service",
    "query": "label_values(envoy_cluster_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Egress CPS / RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_total{envoy_cluster_name=\"$originating_service\"}[1m]))",
     "legendFormat": "egress CPS"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=\"$originating_service\"}[1m]))",
     "legendFormat": "egress RPS"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_total{envoy_cluster_name=\"$originating_service\"}[1m]))",
     "legendFormat": "pending req to"
    },
    {
     "expr": "sum(rate(envoy_cluster_lb_healthy_panic{envoy_cluster_name=\"$originating_service\"}[1m]))",
     "legendFormat": "lb healthy panic RPS"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_active{envoy_cluster_name=\"$originating_service\"}[1m]))",
     "legendFormat": "egress R active"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_active{envoy_cluster_name=\"$originating_service\"}[1m]))",
     "legendFormat": "egress R pending active"
    }
   ]
  },
  {
   "title": "Cluster Membership",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(envoy_cluster_membership_change{envoy_cluster_name=\"$originating_service\"}[1m]))",
     "legendFormat": "membership changes [1m]"
    },
    {
     "expr": "sum(envoy_cluster_membership_total{envoy_cluster_name=\"$originating_service\"})",
     "legendFormat": "total membership"
    },
    {
     "expr": "sum(envoy_cluster_outlier_detection_ejections_active{envoy_cluster_name=\"$originating_service\"})",
     "legendFormat": "outlier ejections active"
    },
    {
     "expr": "sum(envoy_cluster_membership_healthy{envoy_cluster_name=\"$originating_service\"})",
     "legendFormat": "healthy members (active HC and outlier)"
    },
    {
     "expr": "sum(envoy_cluster_health_check_healthy{envoy_cluster_name=\"$originating_service\"})",
     "legendFormat": "healthy members (active HC only)"
    }
   ]
  },
  {
   "title": "Total Connections / Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{envoy_cluster_name=\"$originating_service\"})",
     "legendFormat": "connections"
    },
    {
     "expr": "sum(envoy_cluster_upstream_rq_active{envoy_cluster_name=\"$originating_service\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(envoy_cluster_upstream_rq_pending_active{envoy_cluster_name=\"$originating_service\"})",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"4\",envoy_cluster_name=\"$originating_service\"}[1m])) / (sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=\"$originating_service\"}[1m]))-sum(rate(envoy_cluster_upstream_rq_pending_total{envoy_cluster_name=\"$originating_service\"}[1m]))-sum(rate(envoy_cluster_upstream_rq_cancelled{envoy_cluster_name=\"$originating_service\"}[1m])))",
     "legendFormat": "4xx %"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"3\",envoy_cluster_name=\"$originating_service\"}[1m])) / (sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=\"$originating_service\"}[1m]))-sum(rate(envoy_cluster_upstream_rq_pending_total{envoy_cluster_name=\"$originating_service\"}[1m]))-sum(rate(envoy_cluster_upstream_rq_cancelled{envoy_cluster_name=\"$originating_service\"}[1m])))",
     "legendFormat": "3xx %"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"2\",envoy_cluster_name=\"$originating_service\"}[1m])) / (sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=\"$originating_service\"}[1m]))-sum(rate(envoy_cluster_upstream_rq_pending_total{envoy_cluster_name=\"$originating_service\"}[1m]))-sum(rate(envoy_cluster_upstream_rq_cancelled{envoy_cluster_name=\"$originating_service\"}[1m])))",
     "legendFormat": "2xx %"
    },
    {
     "expr": "(sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"5\",envoy_cluster_name=\"$originating_service\"}[1m]))) / (sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=\"$originating_service\"}[1m]))-sum(rate(envoy_cluster_upstream_rq_pending_total{envoy_cluster_name=\"$originating_service\"}[1m]))-sum(rate(envoy_cluster_upstream_rq_cancelled{envoy_cluster_name=\"$originating_service\"}[1m])))",
     "legendFormat": "5xx %"
    }
   ]
  },
  {
   "title": "Success Rate (non-5xx responses)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=\"$originating_service\"}[1m]))-sum(rate(envoy_cluster_upstream_rq_pending_total{envoy_cluster_name=\"$originating_service\"}[1m]))-sum(rate(envoy_cluster_upstream_rq_cancelled{envoy_cluster_name=\"$originating_service\"}[1m]))-sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"5\",envoy_cluster_name=\"$originating_service\"}[1m])) or sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=\"$originating_service\"}[1m]))-sum(rate(envoy_cluster_upstream_rq_pending_total{envoy_cluster_name=\"$originating_service\"}[1m]))-sum(rate(envoy_cluster_upstream_rq_cancelled{envoy_cluster_name=\"$originating_service\"}[1m])))/ (sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=\"$originating_service\"}[1m]))-sum(rate(envoy_cluster_upstream_rq_pending_total{envoy_cluster_name=\"$originating_service\"}[1m]))-sum(rate(envoy_cluster_upstream_rq_cancelled{envoy_cluster_name=\"$originating_service\"}[1m])))",
     "legendFormat": "Success Rate % (non-5xx)"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"5\",envoy_cluster_name=\"$originating_service\"}[1m])) / (sum(rate(envoy_cluster_upstream_rq_pending_total{envoy_cluster_name=\"$originating_service\"}[1m]))-sum(rate(envoy_cluster_upstream_rq_pending_total{envoy_cluster_name=\"$originating_service\"}[1m]))-sum(rate(envoy_cluster_upstream_rq_cancelled{envoy_cluster_name=\"$originating_service\"}[1m])))",
     "legendFormat": "Failure Rate % (only 5xx)"
    }
   ]
  },
  {
   "title": "Upstream Request Errors",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_connect_timeout{envoy_cluster_name=\"$originating_service\"}[1m]))",
     "legendFormat": "connect timeout"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_failure_eject{envoy_cluster_name=\"$originating_service\"}[1m]))",
     "legendFormat": "pending failure ejection"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_overflow{envoy_cluster_name=\"$originating_service\"}[1m]))",
     "legendFormat": "pending overflow"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_timeout{envoy_cluster_name=\"$originating_service\"}[1m]))",
     "legendFormat": "request timeout"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_per_try_timeout{envoy_cluster_name=\"$originating_service\"}[1m]))",
     "legendFormat": "per try request timeout"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_rx_reset{envoy_cluster_name=\"$originating_service\"}[1m]))",
     "legendFormat": "request reset"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_destroy_local_with_active_rq{envoy_cluster_name=\"$originating_service\"}[1m]))",
     "legendFormat": "destroy initialized from originating service"
    },
    {
     "expr": "sum(rate(envoy_http_downstream_cx_destroy_remote_active_rq{envoy_cluster_name=\"$originating_service\"}[1m]))",
     "legendFormat": "destroy initialized from remote service"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_maintenance_mode{envoy_cluster_name=\"$originating_service\"}[1m]))",
     "legendFormat": "request failed maintenance mode"
    }
   ]
  },
  {
   "title": "Upstream Flow Control",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_flow_control_paused_reading_total{envoy_cluster_name=\"$originating_service\"}[1m]))",
     "legendFormat": "paused reading from destination service"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_flow_control_resumed_reading_total{envoy_cluster_name=\"$originating_service\"}[1m]))",
     "legendFormat": "resumed reading from destination service"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_flow_control_backed_up_total{envoy_cluster_name=\"$originating_service\"}[1m]))",
     "legendFormat": "paused reading from originating service"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_flow_control_drained_total{envoy_cluster_name=\"$originating_service\"}[1m]))",
     "legendFormat": "resumed reading from originating service"
    }
   ]
  },
  {
   "title": "Upstream Request Retry",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry{envoy_cluster_name=\"$originating_service\"}[1m]))",
     "legendFormat": "request retry"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_success{envoy_cluster_name=\"$originating_service\"}[1m]))",
     "legendFormat": "request retry success"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_overflow{envoy_cluster_name=\"$originating_service\"}[1m]))",
     "legendFormat": "request retry overflow"
    }
   ]
  }
 ]
}