---
apiVersion: boom.caos.ch/v1beta1
kind: Toolset
metadata:
  name: caos
  namespace: tooling
spec:
  name: basisset
  prometheus-operator:
    deploy: true
  logging-operator:
    deploy: true
  prometheus-node-exporter:
    deploy: true
  grafana:
    deploy: true
  cert-manager:
    deploy: true
  ambassador:
    deploy: true
  kube-state-metrics:
    deploy: true