---
apiVersion: boom.caos.ch/v1beta1
kind: Toolset
metadata:
  name: caos
  namespace: caos-system
spec:
  kubeVersion: v1.17.0
  prometheus-operator:
    deploy: true
  logging-operator:
    deploy: true
  prometheus-node-exporter:
    deploy: true
  grafana:
    deploy: true
  ambassador:
    deploy: false
  kube-state-metrics:
    deploy: true
  argocd:
    deploy: false
  prometheus:
    deploy: true