{
 "title": "Health / Cluster",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(up{job=~\"caos_remote_(node-exporter|systemd-exporter)\"}, instance)"
   },
   {
    "name": "master",
    "query": "label_values(caos_etcd_server_has_leader, instance)"
   },
   {
    "name": "ingress",
    "query": "label_values(caos_probe{name!=\"httpingress\"}, name)"
   }
  ]
 },
 "panels": [
  { "title": "Ingresses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$ingress VIP",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 1 },
   "repeat": "ingress",
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "min(caos_probe{name=\"$ingress\",type=\"VIP\"})"
    }
   ]
  },
  {
   "title": "$ingress VIP",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "min(caos_probe{name=\"$ingress\",type=\"VIP\"})"
    }
   ]
  },
  {
   "title": "$ingress Upstream",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 3 },
   "repeat": "ingress",
   "format": "percentunit",
   "valueName": "min",
   "targets": [
    {
     "expr": "avg(caos_upstream_probe_ryg{name=\"$ingress\"})"
    }
   ]
  },
  {
   "title": "$ingress Upstream",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 3 },
   "format": "percentunit",
   "valueName": "min",
   "targets": [
    {
     "expr": "avg(caos_upstream_probe_ryg{name=\"$ingress\"})"
    }
   ]
  },
  { "title": "Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "systemd $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "repeat": "instance",
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "caos_systemd_ryg{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "systemd $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "caos_systemd_ryg{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "systemd $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "caos_systemd_ryg{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "systemd $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "caos_systemd_ryg{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "systemd $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "caos_systemd_ryg{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "systemd $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "caos_systemd_ryg{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "memory $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 8 },
   "repeat": "instance",
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "caos_node_memory_ryg{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "memory $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "caos_node_memory_ryg{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "memory $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "caos_node_memory_ryg{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "memory $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "caos_node_memory_ryg{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "memory $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 8 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "caos_node_memory_ryg{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "memory $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 8 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "caos_node_memory_ryg{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "cpu $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 10 },
   "repeat": "instance",
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "caos_node_cpu_ryg{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "cpu $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 10 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "caos_node_cpu_ryg{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "cpu $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 10 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "caos_node_cpu_ryg{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "cpu $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 10 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "caos_node_cpu_ryg{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "cpu $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 10 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "caos_node_cpu_ryg{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "cpu $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 10 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "caos_node_cpu_ryg{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "ready $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 12 },
   "repeat": "instance",
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "min(caos_k8s_node_ryg{node=\"$instance\"})"
    }
   ]
  },
  {
   "title": "ready $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 12 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "min(caos_k8s_node_ryg{node=\"$instance\"})"
    }
   ]
  },
  {
   "title": "ready $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 12 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "min(caos_k8s_node_ryg{node=\"$instance\"})"
    }
   ]
  },
  {
   "title": "ready $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "min(caos_k8s_node_ryg{node=\"$instance\"})"
    }
   ]
  },
  {
   "title": "ready $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 12 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "min(caos_k8s_node_ryg{node=\"$instance\"})"
    }
   ]
  },
  {
   "title": "ready $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 12 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "min(caos_k8s_node_ryg{node=\"$instance\"})"
    }
   ]
  },
  {
   "title": "etcd $master has a leader",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 14 },
   "repeat": "master",
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "caos_etcd_ryg{instance=\"$master\"} OR on() vector(0)"
    }
   ]
  },
  {
   "title": "etcd $master has a leader",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 14 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "caos_etcd_ryg{instance=\"$master\"} OR on() vector(0)"
    }
   ]
  },
  {
   "title": "etcd $master has a leader",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 14 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "caos_etcd_ryg{instance=\"$master\"} OR on() vector(0)"
    }
   ]
  },
  {
   "title": "cluster cpu utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "caos_cluster_cpu_utilisation_5m"
    }
   ]
  }
 ]
}