// Code generated by MockGen. DO NOT EDIT.
// Source: application.go

// Package application is a generated GoMock package.
package application

import (
	v1beta1 "github.com/caos/boom/api/v1beta1"
	name "github.com/caos/boom/internal/name"
	chart "github.com/caos/boom/internal/templator/helm/chart"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockApplication is a mock of Application interface
type MockApplication struct {
	ctrl     *gomock.Controller
	recorder *MockApplicationMockRecorder
}

// MockApplicationMockRecorder is the mock recorder for MockApplication
type MockApplicationMockRecorder struct {
	mock *MockApplication
}

// NewMockApplication creates a new mock instance
func NewMockApplication(ctrl *gomock.Controller) *MockApplication {
	mock := &MockApplication{ctrl: ctrl}
	mock.recorder = &MockApplicationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockApplication) EXPECT() *MockApplicationMockRecorder {
	return m.recorder
}

// Initial mocks base method
func (m *MockApplication) Initial() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initial")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Initial indicates an expected call of Initial
func (mr *MockApplicationMockRecorder) Initial() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initial", reflect.TypeOf((*MockApplication)(nil).Initial))
}

// Changed mocks base method
func (m *MockApplication) Changed(arg0 *v1beta1.ToolsetSpec) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Changed", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Changed indicates an expected call of Changed
func (mr *MockApplicationMockRecorder) Changed(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Changed", reflect.TypeOf((*MockApplication)(nil).Changed), arg0)
}

// Deploy mocks base method
func (m *MockApplication) Deploy(arg0 *v1beta1.ToolsetSpec) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deploy", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Deploy indicates an expected call of Deploy
func (mr *MockApplicationMockRecorder) Deploy(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deploy", reflect.TypeOf((*MockApplication)(nil).Deploy), arg0)
}

// SetAppliedSpec mocks base method
func (m *MockApplication) SetAppliedSpec(arg0 *v1beta1.ToolsetSpec) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAppliedSpec", arg0)
}

// SetAppliedSpec indicates an expected call of SetAppliedSpec
func (mr *MockApplicationMockRecorder) SetAppliedSpec(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAppliedSpec", reflect.TypeOf((*MockApplication)(nil).SetAppliedSpec), arg0)
}

// GetName mocks base method
func (m *MockApplication) GetName() name.Application {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(name.Application)
	return ret0
}

// GetName indicates an expected call of GetName
func (mr *MockApplicationMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockApplication)(nil).GetName))
}

// GetNamespace mocks base method
func (m *MockApplication) GetNamespace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamespace")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNamespace indicates an expected call of GetNamespace
func (mr *MockApplicationMockRecorder) GetNamespace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamespace", reflect.TypeOf((*MockApplication)(nil).GetNamespace))
}

// MockHelmApplication is a mock of HelmApplication interface
type MockHelmApplication struct {
	ctrl     *gomock.Controller
	recorder *MockHelmApplicationMockRecorder
}

// MockHelmApplicationMockRecorder is the mock recorder for MockHelmApplication
type MockHelmApplicationMockRecorder struct {
	mock *MockHelmApplication
}

// NewMockHelmApplication creates a new mock instance
func NewMockHelmApplication(ctrl *gomock.Controller) *MockHelmApplication {
	mock := &MockHelmApplication{ctrl: ctrl}
	mock.recorder = &MockHelmApplicationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockHelmApplication) EXPECT() *MockHelmApplicationMockRecorder {
	return m.recorder
}

// Initial mocks base method
func (m *MockHelmApplication) Initial() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initial")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Initial indicates an expected call of Initial
func (mr *MockHelmApplicationMockRecorder) Initial() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initial", reflect.TypeOf((*MockHelmApplication)(nil).Initial))
}

// Changed mocks base method
func (m *MockHelmApplication) Changed(arg0 *v1beta1.ToolsetSpec) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Changed", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Changed indicates an expected call of Changed
func (mr *MockHelmApplicationMockRecorder) Changed(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Changed", reflect.TypeOf((*MockHelmApplication)(nil).Changed), arg0)
}

// Deploy mocks base method
func (m *MockHelmApplication) Deploy(arg0 *v1beta1.ToolsetSpec) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deploy", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Deploy indicates an expected call of Deploy
func (mr *MockHelmApplicationMockRecorder) Deploy(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deploy", reflect.TypeOf((*MockHelmApplication)(nil).Deploy), arg0)
}

// SetAppliedSpec mocks base method
func (m *MockHelmApplication) SetAppliedSpec(arg0 *v1beta1.ToolsetSpec) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAppliedSpec", arg0)
}

// SetAppliedSpec indicates an expected call of SetAppliedSpec
func (mr *MockHelmApplicationMockRecorder) SetAppliedSpec(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAppliedSpec", reflect.TypeOf((*MockHelmApplication)(nil).SetAppliedSpec), arg0)
}

// GetName mocks base method
func (m *MockHelmApplication) GetName() name.Application {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(name.Application)
	return ret0
}

// GetName indicates an expected call of GetName
func (mr *MockHelmApplicationMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockHelmApplication)(nil).GetName))
}

// GetNamespace mocks base method
func (m *MockHelmApplication) GetNamespace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamespace")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNamespace indicates an expected call of GetNamespace
func (mr *MockHelmApplicationMockRecorder) GetNamespace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamespace", reflect.TypeOf((*MockHelmApplication)(nil).GetNamespace))
}

// GetChartInfo mocks base method
func (m *MockHelmApplication) GetChartInfo() *chart.Chart {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChartInfo")
	ret0, _ := ret[0].(*chart.Chart)
	return ret0
}

// GetChartInfo indicates an expected call of GetChartInfo
func (mr *MockHelmApplicationMockRecorder) GetChartInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChartInfo", reflect.TypeOf((*MockHelmApplication)(nil).GetChartInfo))
}

// GetImageTags mocks base method
func (m *MockHelmApplication) GetImageTags() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImageTags")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// GetImageTags indicates an expected call of GetImageTags
func (mr *MockHelmApplicationMockRecorder) GetImageTags() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImageTags", reflect.TypeOf((*MockHelmApplication)(nil).GetImageTags))
}

// SpecToHelmValues mocks base method
func (m *MockHelmApplication) SpecToHelmValues(spec *v1beta1.ToolsetSpec) interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpecToHelmValues", spec)
	ret0, _ := ret[0].(interface{})
	return ret0
}

// SpecToHelmValues indicates an expected call of SpecToHelmValues
func (mr *MockHelmApplicationMockRecorder) SpecToHelmValues(spec interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpecToHelmValues", reflect.TypeOf((*MockHelmApplication)(nil).SpecToHelmValues), spec)
}

// MockYAMLApplication is a mock of YAMLApplication interface
type MockYAMLApplication struct {
	ctrl     *gomock.Controller
	recorder *MockYAMLApplicationMockRecorder
}

// MockYAMLApplicationMockRecorder is the mock recorder for MockYAMLApplication
type MockYAMLApplicationMockRecorder struct {
	mock *MockYAMLApplication
}

// NewMockYAMLApplication creates a new mock instance
func NewMockYAMLApplication(ctrl *gomock.Controller) *MockYAMLApplication {
	mock := &MockYAMLApplication{ctrl: ctrl}
	mock.recorder = &MockYAMLApplicationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockYAMLApplication) EXPECT() *MockYAMLApplicationMockRecorder {
	return m.recorder
}

// Initial mocks base method
func (m *MockYAMLApplication) Initial() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initial")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Initial indicates an expected call of Initial
func (mr *MockYAMLApplicationMockRecorder) Initial() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initial", reflect.TypeOf((*MockYAMLApplication)(nil).Initial))
}

// Changed mocks base method
func (m *MockYAMLApplication) Changed(arg0 *v1beta1.ToolsetSpec) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Changed", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Changed indicates an expected call of Changed
func (mr *MockYAMLApplicationMockRecorder) Changed(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Changed", reflect.TypeOf((*MockYAMLApplication)(nil).Changed), arg0)
}

// Deploy mocks base method
func (m *MockYAMLApplication) Deploy(arg0 *v1beta1.ToolsetSpec) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deploy", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Deploy indicates an expected call of Deploy
func (mr *MockYAMLApplicationMockRecorder) Deploy(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deploy", reflect.TypeOf((*MockYAMLApplication)(nil).Deploy), arg0)
}

// SetAppliedSpec mocks base method
func (m *MockYAMLApplication) SetAppliedSpec(arg0 *v1beta1.ToolsetSpec) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAppliedSpec", arg0)
}

// SetAppliedSpec indicates an expected call of SetAppliedSpec
func (mr *MockYAMLApplicationMockRecorder) SetAppliedSpec(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAppliedSpec", reflect.TypeOf((*MockYAMLApplication)(nil).SetAppliedSpec), arg0)
}

// GetName mocks base method
func (m *MockYAMLApplication) GetName() name.Application {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(name.Application)
	return ret0
}

// GetName indicates an expected call of GetName
func (mr *MockYAMLApplicationMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockYAMLApplication)(nil).GetName))
}

// GetNamespace mocks base method
func (m *MockYAMLApplication) GetNamespace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamespace")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNamespace indicates an expected call of GetNamespace
func (mr *MockYAMLApplicationMockRecorder) GetNamespace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamespace", reflect.TypeOf((*MockYAMLApplication)(nil).GetNamespace))
}

// GetYaml mocks base method
func (m *MockYAMLApplication) GetYaml() interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetYaml")
	ret0, _ := ret[0].(interface{})
	return ret0
}

// GetYaml indicates an expected call of GetYaml
func (mr *MockYAMLApplicationMockRecorder) GetYaml() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetYaml", reflect.TypeOf((*MockYAMLApplication)(nil).GetYaml))
}
