#!/bin/bash
set -e

function parseYaml {
  local file=$1
  while read -r line
  do
    local k=${line%:*}
    local v=${line#*:}
    [ "$k" == "chartName" ] && chartName=$v
    [ "$k" == "chartVersion" ] && chartVersion=$v
    [ "$k" == "indexName" ] && indexName=$v
    [ "$k" == "indexUrl" ] && indexUrl=$v
  done <"$file"
  # Trim leading space
  chartName="${chartName#"${chartName%%[![:space:]]*}"}"
  chartVersion="${chartVersion#"${chartVersion%%[![:space:]]*}"}"
  indexUrl="${indexUrl#"${indexUrl%%[![:space:]]*}"}"
  indexName="${indexName#"${indexName%%[![:space:]]*}"}"
}
parseYaml $1

helmHome=${TOOLS_HOME}/helm
chartHome=${TOOLS_HOME}/charts
indexProtocol=https

function doHelm {
  helm --home ${helmHome} $@
}

doHelm init --client-only >& /dev/null

if [ -z "$indexName" ]; then
  indexName=stable
else
  doHelm repo add ${indexName} ${indexProtocol}://${indexUrl} >& /dev/null
fi

doHelm repo update >& /dev/null
doHelm fetch --untar --version=${chartVersion} --untardir ${chartHome}/${chartName}-${chartVersion} ${indexName}/${chartName} >& /dev/null

echo "apiVersion: apps/v1
kind: Success
metadata:
  name: ${chartName}-${chartVersion}"