apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: boom
  name: caos-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boom
  namespace: caos-system
  labels:
    app.kubernetes.io/instance: boom
    app.kubernetes.io/part-of: orbos
    app.kubernetes.io/component: boom
    boom.caos.ch/application: boom
spec:
  selector:
    matchLabels:
      control-plane: boom
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: boom
    spec:
      serviceAccountName: boom
      containers:
      - command:
        - /boom
        args:
          - "--enable-leader-election"
          - "-git-crd-private-key"
          - "/secrets/tools-secret/example.rsa"
          - "-git-crd-url"
          - "git@github.com:caos/gitopsexample.git"
          - "-git-crd-path"
          - "boom.yml"
          - "-metricsport"
          - "2112"
          - "-metrics"
        image: boom:latest
        imagePullPolicy: IfNotPresent
        name: manager
        volumeMounts:
          - name: privaterepo-secret
            mountPath: /secrets/tools-secret
            readOnly: true
        ports:
          - name: metrics
            containerPort: 2112
            protocol: TCP
      imagePullSecrets: 
      - name: boomregistry
      terminationGracePeriodSeconds: 10
      volumes:
      - name: "privaterepo-secret"
        secret:
          secretName: privaterepo-secret
