name: Release
on:
  push:
    branches:
    - master
jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
    - name: Source checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        export IMAGE=docker.pkg.github.com/caos/boom/boom
        export TAG_LATEST=${IMAGE}:latest
        docker build --tag ${TAG_LATEST} --file ./Dockerfile .

        export GIT_TAG="v$(npx semantic-release --dry-run --plugins=@semantic-release/commit-analyzer --analize-commits | grep "The next release version is" | sed -ne 's/.*The\ next\ release\ version\ is\ \([0-9]\+\.[0-9]\+\.[0-9]\+\)$/\1/p')"
        [[ "$GIT_TAG" == "v" ]] && echo "Exiting, as no new version needs to be released" && exit 0
        export TAG_VERSION=${IMAGE}:${GIT_TAG}
        docker login docker.pkg.github.com -u ci -p ${GITHUB_TOKEN}
        docker tag ${TAG_LATEST} ${TAG_VERSION}
        docker push ${TAG_LATEST}
        docker push ${TAG_VERSION}

        npx semantic-release